# JamesRandom Ranlux64 MersenneTwister
/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto


################################
# ACQUISITION for 180 projections #
################################
/gate/application/setTimeSlice     1. s
/gate/application/setTimeStart     0.  s
/gate/application/setTimeStop      180. s


#/gate/application/setTotalNumberOfPrimaries 1000000000
/gate/application/setNumberOfPrimariesPerRun 2000000000
/gate/application/start
