/gate/world/daughters/name fash
/gate/world/daughters/insert ImageRegularParametrisedVolume 
/gate/fash/geometry/setImage abdomen_supine.dcm
/gate/fash/geometry/setRangeToMaterialFile fashrange.dat
/gate/fash/placement/setTranslation 0. 1. 0. mm
/gate/fash/placement/setRotationAxis 1 0 0
/gate/fash/placement/setRotationAngle 90. deg

/gate/fash/attachPhantomSD

/gate/fash/moves/insert rotation
/gate/fash/rotation/setSpeed 1. deg/s
/gate/fash/rotation/setAxis 0 0 1

/gate/fash/setSkipEqualMaterials 1
